#!/usr/bin/env python3

import socket

HOST = input('Введите IP адрес сервера: ')
PORT = 1560

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    data = s.recv(1024).decode()
    print('Текущее время:', data)
